FROM wordpress:fpm

#############
# APT TOOLS #
#############
RUN set -ex; \
    apt-get update && apt-get install -y sendmail libldap2-dev iputils-ping telnet less; \ 
    apt-get purge -y --auto-remove; \
    rm -rf /var/lib/apt/lists/*

#######
# PHP #
#######

# Install PHP Extensions
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions; \
    install-php-extensions memcached xdebug ldap calendar gettext pdo_mysql sockets xsl

# Configure PHP Extensions
## Xdebug
RUN {\
        echo 'zend_extension=xdebug.so'; \
        echo 'xdebug.mode=debug,develop; develop: prettier `var_dump`, debug: enables step debugger'; \
        echo 'xdebug.start_with_request = yes;'; \
        echo 'xdebug.client_host = host.docker.internal;'; \
    } > /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

# Configure PHP Environment 
COPY ./conf/php.ini.dev $PHP_INI_DIR/conf.d/custom.ini

###############
# OTHER TOOLS #
###############

# install wp-cli
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp
RUN echo 'path: /var/www/html' > /wp-cli.yml

########
# MODS #
########

# Give wp-cli write access
RUN chown www-data:www-data /var/www
USER www-data
SHELL ["/bin/bash"]
